### ISSUE TITLE
There might be dependencies problem in settings

### ISSUE THREAD

**Issue by vnikolayev1** [katyukha/odoo-helper-scripts#16]
steps to reproduce: 
``` odoo-install -i . --db-user odoo13 --conf-opt-http_port 8999 --odoo-version 13.0 --odoo-branch 13.0```
ERROR: Cannot install -r /tmp/tmp.1LIf1OFTuu (line 7) and greenlet==0.4.10 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested greenlet==0.4.10
    gevent 1.3.4 depends on greenlet>=0.4.13; platform_python_implementation == "CPython"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
ERROR: Cannot install python dependencies.

**Comment by vnikolayev1** [comment]
just received answer that it's fixed on dev ```sudo odoo-helper system update dev``` (temporary solution)

**Comment by katyukha** [comment]
The fix is added by commit d9fc2260001ee9fb5bf8a97ad824da79f4058e63 and will be available in next release.
Currently, it is required to switch to *dev* version to apply this fix
