### ISSUE TITLE
while try use odoo-helper-db "lodoo: command not found "

### ISSUE THREAD

**Issue by karabanov-volodymyr** [katyukha/odoo-helper-scripts#18]
**Describe the bug**
while try use odoo-helper-db "lodoo: command not found "

**To Reproduce**
sudo odoo-helper-db list

sudo: lodoo: command not found
ERROR: Cannot get list of databases!

**Comment by katyukha** [comment]
Hi,

Recently, the project was changed to use `lodoo` installed from pypi, instead of using bundled one.
To fix this, you can run following command, that will update all python dependencies for specific odoo-helper project:

```bash
odoo-helper install py-prerequirements
```

**Comment by katyukha** [comment]
Closing, seems to be answered.
