### ISSUE TITLE
odoo-helper start prints stderr to console

### ISSUE THREAD

**Issue by ldhieu** [katyukha/odoo-helper-scripts#5]
This problem happens with:
`odoo-helper start`
or `odoo-helper addons update -d $database $module_name`

This problem still happens even with `unbuffer` installed (from expect + tclsh package)

This problem happens on Debian Stretch.

When run, `odoo-helper start` will continue printing out messages such as

```
192.168.122.2 - - [2017-08-29 11:40:19] "POST /longpolling/poll HTTP/1.0" 200 330 51.760627
192.168.122.2 - - [2017-08-29 11:40:26] "POST /longpolling/poll HTTP/1.0" 200 305 50.867880
192.168.122.2 - - [2017-08-29 11:40:30] "POST /longpolling/poll HTTP/1.0" 200 329 50.049836
192.168.122.2 - - [2017-08-29 11:40:31] "POST /longpolling/poll HTTP/1.0" 200 304 50.145807 
```
Other messages go to syslog/logfile just fine.

This breaks CI/CD because runner stops and does not return.

**Comment by katyukha** [comment]
Hello!

What version of odoo is installed?
And what version of odoo-helper-scripts used (`odoo-helper --version`)?

**Comment by ldhieu** [comment]
Hello @katyukha 

Here are the outputs, sorry I didn't include it:
```
odoo@gin:~/2g$ odoo-helper --version
Version: 0.1.2-dev
Branch: HEAD
Commit: 5e7b0a2
```

```
ODOO_VERSION=10.0;
ODOO_BRANCH=10.0;
PROJECT_ROOT_DIR=/var/lib/odoo/2g;
CONF_DIR=/var/lib/odoo/2g/conf;
LOG_DIR=/var/lib/odoo/2g/logs;
LOG_FILE=/var/lib/odoo/2g/logs/odoo.log;
LIBS_DIR=/var/lib/odoo/2g/libs;
DOWNLOADS_DIR=/var/lib/odoo/2g/downloads;
ADDONS_DIR=/var/lib/odoo/2g/custom_addons;
DATA_DIR=/var/lib/odoo/2g/data;
BIN_DIR=/var/lib/odoo/2g/bin;
VENV_DIR=/var/lib/odoo/2g/venv;
ODOO_PATH=/var/lib/odoo/2g/odoo;
ODOO_CONF_FILE=/var/lib/odoo/2g/conf/odoo.conf;
ODOO_TEST_CONF_FILE=/var/lib/odoo/2g/conf/odoo.test.conf;
ODOO_PID_FILE=/var/lib/odoo/2g/odoo.pid;
BACKUP_DIR=/var/lib/odoo/2g/backups;
REPOSITORIES_DIR=/var/lib/odoo/2g/repositories;
```

**Comment by katyukha** [comment]
Is there any access rights restrictions?
what it in your /var/lib/odoo/2g/conf/odoo.conf?
What user used to run odoo?

I have tried to reproduce this bug in Debian Stretch (using docker), but only installation of odoo caused some errors: some deb packages was removed in Stretch, some dependencies were not installed automaticaly. That was partly fixed in last commits on dev branch. But commands like `odoo-helper start` worked fine.

Also, attach, please, output of following command:

```bash
bash -x $(command -v odoo-helper) start
```

- `bash -x` here is to print debug log
- `$(command -v odoo-helper)` here is to get path to odoo-helper script

I will try again to reproduce this bug soon...

**Comment by katyukha** [comment]
Hello @ldhieu , few more notes...

May be `odoo-helper server run` will be better for you?
The difference, betwen `start` and `run` is that, `start` command starts odoo server in background, and returns (similar to `odoo-bin -c $config &`). `run` command instead starts odoo server in foreground (similar to `odoo-bin -c $config`). Both commands automaticaly set odoo config via environment variables.

Also, if you play with output redirection, both streams *STDERR* and *STDOUT* should be redirected to logs.

Last commits on *dev* branch, make installations of odoo via odoo-helper-scripts work fine for debian:stretch with one exception: wkhtmltopdf installation fails, but it is not critical.

**Comment by ldhieu** [comment]
Thank you @katyukha -

Debian Stretch installs from scratch is now fine and STDERR stopped printing onto terminal.

I'll close this issue if that's alright with you.

Cheers,
H
