### ISSUE TITLE
db create will always load demo data

### ISSUE THREAD

**Issue by ldhieu** [katyukha/odoo-helper-scripts#8]
https://github.com/katyukha/odoo-helper-scripts/blob/6b231150e276e59739d4983de3b0edca7cfb77a8/lib/db.bash#L70

This has quotes around $demo_data, while $demo_data defaults to False, but due to quotes, makes it a non-empty string meaning True, therefore db create will always have demo data in it.

**Comment by katyukha** [comment]
Fix already on dev branch. Seems to be working)
